name: cgv_demo_flutter_firebase
description: A Flutter app with Firebase reuse
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  clevertap_plugin: 3.3.1
  geolocator: ^14.0.1      
  permission_handler: ^12.0.0 
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
